FROM golang:1.8

# setting working directory
WORKDIR /go/src/app
##COPY / /go/src/app

# installing dependencies
RUN go get github.com/gorilla/mux
RUN go get github.com/smartystreets/goconvey

EXPOSE 10010
#RUN chmod a+x /go/src/app/entrypoint.sh
#ENTRYPOINT ["/go/src/app/entrypoint.sh"]